# Generated by Django 4.1.1 on 2022-09-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\Chen\\Desktop\\opencvAPI\\media\\original'),
        ),
    ]
